<?php
namespace SCC\Console\Event;
/**
 * New autogenerated command
 */
class DisableListenerCommand implements \SCC\Console\ConsoleCommand {
	/**
	 * {@inheritdoc}
	 */
	function onCommand(array $params): void {

		if (isset($params[0])) {
			$alias = $params[0];
		} else {
			echo "Введите псевданим псевданим слушателя: ";
			$alias = fgets(STDIN);
			if (substr($alias, -1) === "\n")
				$alias = substr($alias, 0, -1);
		}

		$state = \SCC\State($alias,"events");
		if (!$state->exists()) {
			echo "Событие с таким псевданимом не существует";
			return;
		}

		if (isset($params[1])) {
			$classPath = $params[1];
		} else {
			echo "Введите путь к класу слушателя: ";
			$classPath = fgets(STDIN);
			if (substr($classPath, -1) === "\n")
				$classPath = substr($classPath, 0, -1);
		}

		$listeners = $state->get("listeners",[]);
		$listenerKey = null;

		foreach ($listeners as $key => $listener) {
			if ($classPath === $listener["path"]) {
				$listenerKey = $key;
				break;
			}
		}
		if ($listenerKey !== null) {
			unset($listeners[$listenerKey]);
			$state->set("listeners",$listeners);
			$state->save();
		} else {
			echo "Слушатель с таким путем не найден";
		}
	}
}
